### ISSUE TITLE
Support for GitHub App auth

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#146]
# TODOs

- [x] Interfaces and implementation
- [x] Cache support for storing issued tokens.  Helps avoid eating API limits.
- [x] Encrypted cache support for securely storing token cache at rest.
- [x] API Documentation
- [x] Unit tests

# Other info

Companion shell script for testing

```bash
#!/bin/bash
set -e

if [ -z "${JWT_TOKEN:-}" ]; then
  echo 'Missing GitHub JWT token.' >&2
  exit 1
fi

curl=( curl -sSfL -H "Authorization: Bearer $JWT_TOKEN"  -H "Accept: application/vnd.github+json" )

if [ -z "${DEBUG:-}" ]; then
  curl+=( -sSfL )
fi

# https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps
function getInstallationId() {
  "${curl[@]}" https://api.github.com/app/installations | jq '.[].id'
}


id="$(getInstallationId)"
"${curl[@]}" -d '{"repositories": ["sandscape", "documentation"], "permissions": {"contents": "read"}}' \
  https://api.github.com/app/installations/"$id"/access_tokens
```

Groovy usage
```groovy
import net.gleske.jervis.tools.securityIO

String key = '''
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
'''.trim()

def security = new securityIO(key)
String jwt = security.getGitHubJWT('1234')
println "Signature Verified: ${security.verifyGitHubJWT(jwt)}"
jwt
```

**Comment by samrocketman** [comment]
JWT support implemented

https://github.com/samrocketman/jervis/commit/3a093b9551498c8f6263b9f7881c6b0e3b95767f

**Comment by samrocketman** [comment]
https://stackoverflow.com/questions/73503293/convert-pkcs8-private-key-to-pkcs1-private-key-using-java

**Comment by samrocketman** [comment]
PKCS8 support implemented

https://github.com/samrocketman/jervis/commit/80166596b4a05d1cf3b484c4d7b5f4e5ca8619fa

**Comment by samrocketman** [comment]
For caching ephemeral tokens in Jenkins it might make sense to store the encrypted credentials on disk.

```groovy
import java.nio.channels.FileLock
// java.io.RandomAccessFile
// java.io.File

java.io.File.metaClass.getTextWithLock { ->
    FileLock lock
    final RandomAccessFile fileaccess = new RandomAccessFile(getAbsoluteFile(), 'rw')
    String contents
    try {
        while( !(lock=fileaccess.getChannel().tryLock()) )  {
            // sleep up to half a second
            sleep(new Random().nextInt(500))
        }
        contents = getText()
    } finally {
        if(lock) {
            lock.close()
        }
        fileaccess.close()
    }
    contents ?: ''
}
java.io.File.metaClass.withLockedWriter { Closure body ->
    if(!exists()) {
        createNewFile()
    }
    FileLock lock
    final RandomAccessFile fileaccess = new RandomAccessFile(getAbsoluteFile(), 'rw')
    String contents
    try {
        while( !(lock=fileaccess.getChannel().tryLock()) )  {
            // sleep up to half a second
            sleep(new Random().nextInt(500))
        }
        withWriter(body)
    } finally {
        if(lock) {
            lock.close()
        }
        fileaccess.close()
    }
}

(new File('/tmp/foo')).withLockedWriter { Writer w ->
    w << 'hello'
}

new File('/tmp/foo').getTextWithLock()
```

This would need to be handled by exclusive access with locks in Jenkins.

**Comment by samrocketman** [comment]
Brain storming usage.
```groovy

// https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app
def app = new GitHubAppCredential(github_app_id)
// repository scopes
app.scope = [:]
// ID can be manually selected or the first one auto-detected will be used.
app.installation_id = 1234
app.privateKeyResolver = {->
    new File('').text
}
// date parse
import java.time.Instant

Instant.parse("2016-07-11T22:14:10Z")
```

**Comment by samrocketman** [comment]
How an API client would use it.

```groovy
app.getToken()
// 1. Checks for token expired
// 2. If not expired returns token.
// 3. Create JWT
// 4. Request scoped token.
// 5. Return token
```

**Comment by samrocketman** [comment]
Consider using key-value storage for caching.  

* https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/core/src/main/java/hudson/model/FingerprintMap.java
*
which extends https://github.com/jenkinsci/jenkins/blob/082634cf1e4ef91cac8c82815e52046083722e36/core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
* implements https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/core/src/main/java/hudson/util/KeyedDataStorage.java
* used by https://github.com/jenkinsci/jenkins/blob/082634cf1e4ef91cac8c82815e52046083722e36/core/src/main/java/hudson/model/Fingerprint.java

**Comment by samrocketman** [comment]
Hashing installation ID will cause an unnecessary API request.  Instead credential ID with scope should be sufficient

**Comment by samrocketman** [comment]
API documentation is complete. Good enough leading up to https://github.com/samrocketman/jervis/commit/d29ed70f571b569996f06e252208d83eb0bf9236

**Comment by samrocketman** [comment]
Full support is now available with an encrypted EphemeralTokenCache using a CipherMap.

The token cache can handle many independent expirations.
